### ISSUE TITLE
The 2nd draft

### ISSUE THREAD

**Issue by donho** [notepad-plus-plus/userDefinedLanguages#10]
In order to improve the usability of userDefinedLanguages repository, `udl-list.md` has been added.
With `udl-list.md`, users don't need to deal with `udl-list.json`, a simple mouse click will get what they want.
That makesone more file to modify for the contributor, but it increases the usability of this repository considerably, IMO.

Please let me know if you have other suggestion/opinion.

**Comment by pryrt** [comment]
I agree that there should definitely be a human-readable / easily-clickable list, and a table in the `.md` file works well for that.

**Comment by chcg** [comment]
See https://github.com/notepad-plus-plus/nppPluginList/pull/177 which did add such a list creation for the pluginlist to the python script. Likely this could be adapted also for this repo.

**Comment by pryrt** [comment]
Ah, interesting.  If I read that right, it seems to happen in the validation step.  Can that validation write back to the repo, to automate creating the human-readable list? Or have I misunderstood?  (I am not an expert on the external actions from GitHub)

**Comment by chcg** [comment]
@pryrt I'm not sure about the possibility to commit and push from within a github action. Typically an artefact would be stored by the action which then could be added manually. The first one I have to search the internet for.

**Comment by mattesh** [comment]
@donho, @chcg,
isn't it at the time when a new release is created, when the list need to be generated and pushed into https://github.com/notepad-plus-plus/npp-usermanual ?
This would become triggered with https://help.github.com/en/actions/reference/events-that-trigger-workflows#release-event-release right?
Question 1: do we want the plugin list md files in usermanual to have a history or only the latest?
Question 2: should it be a direct push or pull request, allowing a double confirmation in usermanual?

In terms of the action my intuitive way forward would be a script to 
1. clone npp-usermanual into workspace,
2. generate the new md file(s)
3. create a commit with details from npp-pluginlist
4. push this to the npp-usermanual 

Regards, Mattes

**Comment by chcg** [comment]
@mattesh 
release event sounds reasonable. Why should it be part of the user manual?
ad 1, if we add the md file to this repo we have the history via git. I don't think a history apart from the version number needs to be visible within the file content.
ad 2, I think the step could be part of the existing CI action. There is already a checkout and I think an action could also do a commit and direct push on releases

**Comment by mattesh** [comment]
@chcg,
fine for me. We would put the files to version control and remove them from .gitignore again?
Will you do the yml change?
