### ISSUE TITLE
No Z-Sharp (Z#)

### ISSUE THREAD

**Issue by KostyaTheSon** [notepad-plus-plus/userDefinedLanguages#103]

**Comment by pryrt** [comment]
The maintainers of this UDL repository are here to facilitate adding UDLs that other people have already created to the repository/list.  We are not able to create a brand new UDL every time someone finds a language that doesn't have a UDL yet (we don't necessarily know the language, and it really takes a user of a language to make a good UDL for that language).

Instead, we rely on users to submit the UDLs that they created to share with the Notepad++ user-base at large.  

So if you have a Z# UDL that you'd like to share here, feel free to submit it as a pull request -- or at least attach the XML to this issue and "reopen"

**Comment by KostyaTheSon** [comment]
No Z# dont have UDL. it have SDL

**Comment by pryrt** [comment]
"UDL" in this context is a User Defined Language for Notepad++ -- the way of defining syntax highlighting for langauges that aren't built into Notepad++ -- it is not something inherent to Z# itself.  I was trying to tell you that we will not fill out the User Defined Language dialog in Notepad++ for you.  If you create a UDL definition for the Z# language, and want to share it with other Notepad++ users, then you may feel free to create it and then share it here.  

I have no idea what the "SDL" means in relation to Z# (maybe a Specification and Description Language, or maybe a Simple DirectMedia Layer -- but none of those matter at all to creating a User Defined Langauge to do Z# syntax highlighting in Notepad++)
