### ISSUE TITLE
PowerShell UDL not working

### ISSUE THREAD

**Issue by kumar007git** [notepad-plus-plus/userDefinedLanguages#105]
I copied (per instructions) the PowerShell UDL and put the file in UserDefinedLanguages folder. But, the powershell keywords highighting is not working. Any help? Thanks.

**Comment by pryrt** [comment]
That same file, using the builtin lexer with **Language > P > PowerShell** (or **Language > PowerShell** if you don't have the simplified-menus option set):
![image](https://user-images.githubusercontent.com/17455758/187278322-a704ef64-25d0-43e9-b386-bba069e60a31.png)

It doesn't know CIM_DataFile as a keyword.  But if that, or other such keywords, are important to you, **Settings > Style Configurator > PowerShell** has boxes for user-defined keywords in the INSTRUCTION WORD, CMDLET, ALIAS. and COMMENT DOC KEYWORD lists, so maybe you can use one of those user-defined keywords boxes to add extra keywords.

**Comment by kumar007git** [comment]
Thank you for your response. I was trying to use the UDL XML to see how UDL works and also to use it as a reference to create additional UDL. I am using Dark mode and using DarkModeDefault theme. No matter, what I do I cannot seem to get the UDL XML to work.

**Comment by pryrt** [comment]
> No matter, what I do I cannot seem to get the UDL XML to work.

Unfortunately, until you answer all of my follow-on questions, which I previously asked, I am unable to help you further.  As I showed with my screenshot, it works for me.

**Comment by pryrt** [comment]
If you decide you are willing to share more details, you can re-open this issue.
Closed for now
