### ISSUE TITLE
validation: make homepage attribute optional

### ISSUE THREAD

**Issue by pryrt** [notepad-plus-plus/userDefinedLanguages#12]
@chcg, per https://github.com/notepad-plus-plus/userDefinedLanguages/pull/11#issuecomment-582187447, please make homepage attribute optional

**Comment by chcg** [comment]
@pryrt Should it be still possible to have the homepage with an empty string or just omitted completely?

See https://github.com/chcg/userDefinedLanguages/commit/54b94df5fde497d4b6d7e23f8094e9fcfbb02594

vs.

https://github.com/chcg/userDefinedLanguages/commit/233efb457a1acb98f5d904ac712aecc1e4b31ab5

**Comment by pryrt** [comment]
> @pryrt Should it be still possible to have the homepage with an empty string or just omitted completely?
> 
> See [chcg@54b94df](https://github.com/chcg/userDefinedLanguages/commit/54b94df5fde497d4b6d7e23f8094e9fcfbb02594)


I'd say the one that allows populated, empty string, or not existing.  It gives the most flexibility, and I cannot think of a good reason to _not_ allow empty string.  I wouldn't think that the code for `if homepage attribute does not exist or homepage attribute contains empty string` is that much more difficult to implement than `if homepage attribute does not exist`.  But if you thought it was going to be significantly easier to implement the automation of json->human-readable-list without the extra possible condition (ie, if I hadn't thought of an edge case which makes my pseudocode `if` block not sufficient), I could easily be convinced that we don't need to allow for empty-string possibility.

**Comment by chcg** [comment]
@pryrt Done. Additionally I removed the homepage entries with empty string for homepage but that is not required by the schema. Just to shorten the json.

**Comment by pryrt** [comment]
closed by earlier merge.  thanks
