### ISSUE TITLE
https://github.com/notepad-plus-plus/userDefinedLanguages

### ISSUE THREAD

**Issue by drosenba** [notepad-plus-plus/userDefinedLanguages#123]
The instructions for installing a UDF could be improved.
[https://github.com/notepad-plus-plus/userDefinedLanguages](https://github.com/notepad-plus-plus/userDefinedLanguages)

It says "1. ... click on the copy raw contents button, which will immediately place the raw contents in your clipboard for pasting", but then says "2. ...Import **the file** by placing the file in your userDefineLangs folder...".   The "raw contents in clipboard" is not "the file".  
Additionally, it would be helpful to mention the menu item Language > User Defined Language > Open User Defined Language Folder.

1. Download the XML file ...
  - In Notepad++. Menu item Language > User Defined Language > Open User Defined Language
  - Copy the path from File Explorer address bar
  - From the UDL list ...
  -   ...
       Click on Raw
       Right-click web page, and select "Save as".  Paste the save path in front of the file name. ...

**Comment by pryrt** [comment]
> The "raw contents in clipboard"  is not "the file"

The "raw contents in clipboard" _is_ "the file" if you used the button on the right, which has the "Copy raw contents" hover text.
![](https://user-images.githubusercontent.com/17455758/185504202-754541f7-ee6f-4e77-9a6b-2338448e0dfa.png)

... I had hoped that that my screenshot was clear enough.  But obviously, it is not.  I guess I will have to clarify that even more.

I will also try to work in the "Open User Defined Language Folder" hint

**Comment by drosenba** [comment]
Yes, it is a little confusing because getting "file contents" is not quite the same as getting "the file" (into the folder), which is ultimately what is needed.  Thanks.

(Maybe Notepad++ just needs another menu option ;) since it could just download the file, like you could with curl:
**curl -o C:\Users\me\AppData\Roaming\Notepad++\userDefineLangs\SomeUDL.xml https://github.com/notepad-plus-plus/userDefinedLanguages/blob/master/UDLs/SomeUDL.xml**

**Comment by rdipardo** [comment]
While this is open, it could be pointed out that the "Copy raw contents" option is not universally supported by web browsers.

Yes, it works in Chrome and Microsoft's Edge clone, which is to say ~80% of the world's users, if [StatCounter] can be believed. But Firefox, Safari and Opera are all exceptions.

||||
|:--|:--|:--|
|Edge (Chromium)|Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36 Edg/105.0.1343.53|![MSEdge]|
|Firefox|Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:105.0) Gecko/20100101 Firefox/105.0|![FF]|
|Opera|Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.5112.102 Safari/537.36 OPR/90.0.4480.84|![Opera]|
|Safari (by hacking the user agent string in the "Network conditions" panel)|Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.3 Safari/605.1.15|![Safari(Mac)]|

I'm sure browser quirks are just a tiny contributor to the confusion some users have experienced. Still, it might be better to encourage clicking the "Raw" button, and saving the plain text resource it links to. It's the one universally supported option across browsers (even mobile ones).

[StatCounter]: https://gs.statcounter.com/browser-market-share/desktop/worldwide
[MSEdge]:https://user-images.githubusercontent.com/59004801/193192183-6704917d-f6e5-46b7-8351-687402421043.png
[Safari(Mac)]: https://user-images.githubusercontent.com/59004801/193192773-0d635e65-80b0-4e4b-8b44-b836224d35cd.png
[FF]: https://user-images.githubusercontent.com/59004801/193192287-30236b5b-ac69-41aa-b3f7-a1aa147412d6.png
[Opera]:https://user-images.githubusercontent.com/59004801/193192407-e68b99d2-f5b0-49dd-9abf-66ef8a872d05.png

**Comment by pryrt** [comment]
> the "Copy raw contents" option is not universally supported by web browsers

I didn't know that: it surprises me that Firefox and Opera don't support it.  (Since at home I use Chrome, and at work I use Edge, I hadn't used a browser that didn't have it.)

> even mobile ones

Given that Notepad++ doesn't run on mobile, that wasn't a consideration in my mind.  

But having only two major browsers (or two, since modern MS Edge uses Chromium under the hood) support that button _is_ a good reason.  Given that lack of support, I will remove the references to it before merging the PR

**Comment by pryrt** [comment]
@drosenba and @rdipardo , 

does [this newer version](https://github.com/notepad-plus-plus/userDefinedLanguages/blob/cd7774f5f51a360ab171c1cd38b4a349b857af3b/README.md) describe the process better?

**Comment by drosenba** [comment]
Yes, much better.  One minor addition might be that after "... find the right userDefineLangs\ folder to place your UDL definition file...", you mention to **copy the path from file explorer address bar**, to be later pasted into Save As dialog.
Thanks.

**Comment by pryrt** [comment]
Done and merged.  Thanks for your input.
