### ISSUE TITLE
allow authors to remove their UDL or link from repo

### ISSUE THREAD

**Issue by pryrt** [notepad-plus-plus/userDefinedLanguages#13]
per https://github.com/notepad-plus-plus/userDefinedLanguages/pull/11#issuecomment-582178083, need to indicate to authors that they are allowed to remove their UDL (or even links to them) from the repo.

**Comment by pryrt** [comment]
Something like
> We populated the initial UDLs available based on the old NppWiki++ list of UDLs (archived at [archive.org](https://web.archive.org/web/20180814202307/http://docs.notepad-plus-plus.org/index.php/User_Defined_Language_Files)), assuming that 
>
> The original author of any UDL in this Collection may [request](https://github.com/notepad-plus-plus/userDefinedLanguages/issues) that we remove it from the Collection (or submit a PR to do the same), and we will oblige.

Still need to decide on README, CONTRIBUTING, or both.

**Comment by donho** [comment]
In readme.md under `Submitting your UDL to the Collection` section should be enough.
