### ISSUE TITLE
Language Menu  too long

### ISSUE THREAD

**Issue by aranapatona** [notepad-plus-plus/userDefinedLanguages#143]
The Language menu was already long , too many entries, and having added some custom definitions has made it annoyingly long, can that menu be edited by user? so to group languages by letter or at the very least allow mouse scroll wheel support for it, those up and down arrows are really ugly to handle. 
 
<img src="https://user-images.githubusercontent.com/19786351/212444278-5e64ead6-3c40-4e13-8712-8ae4b533c66e.png" alt="Long Language Menu" width="500"/>

**Comment by pryrt** [comment]
The userDefinedLanguages repository is only used for storing UDL that users define and submit.

There is of course an option in Notepad++ to collapse the built-in languages alphabetically , but it doesn't currently affect the UDL in the same menu.  If you would like it to affect both, or if you want a separate option to collapse the UDL list as well, please clarify and then I think I can transfer this request to the main application issues tracker.

**Comment by aranapatona** [comment]
Collpasing the builtin one would be enough,how is it done?

**Comment by pryrt** [comment]
[Settings > Preferences > Language](https://npp-user-manual.org/docs/preferences/#language) > **☑ Make language menu compact**
