### ISSUE TITLE
An alternate autocomplete xsd file to validate autocomplete files.

### ISSUE THREAD

**Issue by swgmike** [notepad-plus-plus/userDefinedLanguages#154]
[NotepadPlus.txt](https://github.com/notepad-plus-plus/userDefinedLanguages/files/10582138/NotepadPlus.txt)

Note: Github drag and drop doesn't support xsd file extension. Thus, just rename attached txt file with xsd extension.

Here's a more complete autocomplete xml file validator. It uses noNamespaceSchemaLocation  vs. schemaLocation.

The autocomplete xml file should have this in its NotePadPlus tag.  For testing one can specify a directory path somewhere else.

<NotepadPlus
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="file:///C:/Program Files/Notepad++/autoCompletion/NotepadPlus.xsd"

>

**Comment by pryrt** [comment]
> The autocomplete xml file should have this in its NotePadPlus tag. For testing one can specify a directory path somewhere else.

If it _requires_ changes to the XML file to get it to work properly, I'm not going to be able to use it for the validation in this repository.  I thought the XML Tools had an option to allow you to validate against a chosen XSD even if there wasn't a link in the XML -- but I am not an XML Tools expert or XML expert.

Also, as @swgmike suggested in [the forum](https://community.notepad-plus-plus.org/post/83862), if @vinsworldcom wants to share his autoCompletion and userDefineLangs XSD as well, I can play around this weekend but in the repo and in my copy of N++ with XML Tools , to see what I can learn about how these things all work together.

**Comment by pryrt** [comment]
> If it _requires_ changes to the XML file to get it to work properly, I'm not going to be able to use it for the validation in this repository.

By saying that, I didn't mean to imply that if it doesn't work here, I will just ignore it or reject it or whatever.  I'll try to figure out _somewhere_ else to house it, even if it's just included with the User Manual.

**Comment by swgmike** [comment]
Well, to do validation, the validation of the xml has to know where to look for the schema template.  One can point to a file on ones hard disk via one of the schema location attributes by specifying a directory file path, or point to a website webpage and the filename stored there. Don't confuse the xml url/uri/urns used as namespaces  assuming the tool needs to retrieve something. Xml docs state that it only provides namespace uniqueness.  

Morever, if one doesn't want the directory path, then the schema xsd file must be in the same directory as the autocomplete xml files with the following change to the autocomplete xml file. note: these posts aren' showing the closing arrow, but only during editing.

<NotepadPlus
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="NotepadPlus.xsd"
>

**Comment by pryrt** [comment]
I am still not understanding.  In the python lxml library that is used for the CI tests in this repo, I can just load the XML (which has no namespace information, no schema location information) into lxml, then separately load the XSD (from any directory I want), and then lxml is able to validate the XML against the XSD that I loaded.  If it's just a limitation of XML Tools, I'm not sure I want to cater to it.

No: If I run **XML Tools > Validate now** on one of the builtin autoCompletions (that doesn't have the xmlns:xsi and xsi:noNamespcaeSchemaLocation attributes), it just pops up a dialog asking for them.  You can just type it in, without having to edit the XML before validating it.  That dialog does indicate you _may_, if you want to avoid the question, but it's not required.  And when I do, it runs the validation, even though the XML doesn't have the mlns:xsi and xsi:noNamespcaeSchemaLocation attributes.  It's not actually required.

**Comment by pryrt** [comment]
On to the contents of the validation:
The first builtin autoCompletion XML that I tried (perl.xml) showed me:
![image](https://user-images.githubusercontent.com/17455758/216704256-69bed3a0-770e-45be-88f8-66f7af2a3a46.png)

The XSD is claiming that `language` is a _required_ attribute for `<AutoComplete>` tag.  But it's not.  See the documentation in the User Manual, for example:
![image](https://user-images.githubusercontent.com/17455758/216704520-db79c008-3c77-4847-9d15-8e8034e78a32.png)

So it may take some more tweaking to make the XSD actually accept all the perfectly-valid autoCompletion XML files that are already known-good.

**Comment by swgmike** [comment]
Thats why if there are misinterpretations of the autocomplete file, it can be modified.  Thus change it to "optional" instead of "required". So I assume after making this change it will get thru the rest of the file.
For my DXL autocomplete, I set the language attribute value to "DXL".  I think the C language did that and I imitated it.

At least you know that the xsd I submitted is finding things and is more informative than without it.

The more eyes looking at the better.

**Comment by pryrt** [comment]
Yeah, if I change the `language` from `use="required"` to `use="optional"` on line 260 of the XSD, the perl.xml validates just fine (though I think it should also be changed on 142, which seems to define that same restriction, but might not ever be referenced).  

But that run also shows that we don't have to require changing the autoCompletion XML just to get XML Tools to validate: if users don't choose to change their XML, they can just manually choose the XSD path through the dialog.  The instructions can include both.  That makes me feel better.  

I haven't yet tried to validate all the bundled autoCompletion files, or all the ones already in the UDL repo... but if this XSD (after the changes I mentioned) ends up working on all of them, then we're back on track for moving forward.

**Comment by swgmike** [comment]
One thing that might happen is if one puts an xml comment in an autocomplete tag that supposed to contain no data, the xsd may find it vs be smart and know that it is an xml comment that original writer wanted to put thre to explain things. . It depends on the validator.

I guess its better than nothing....when trying to find issues with a large number of functions like the DXL with 1500+

**Comment by swgmike** [comment]
In addition the benefit of the xsd is that when xmltools has enable auto validation that upon saving the xml file that it will tell you if you have any errors or not.

**Comment by vinsworldcom** [comment]
[xmlcheck.zip](https://github.com/notepad-plus-plus/userDefinedLanguages/files/10582817/xmlcheck.zip)

Put the XSD and DTD files in their respective subdirectories of your Notepad++ installation.  Then, from the directory where `notepad++.exe` exists, run the `xmlcheck.bat` program (no arguments necessary.

```
PS MVINCENT C:\usr\bin\npp64 > C:\Users\mvincent\Desktop\xmlcheck.bat
-= autoCompletion =-
actionscript.xml validates
asn1.xml validates
autoit.xml validates
baanc.xml validates
bash.xml validates
batch.xml validates
c.xml validates
...
```

Cheers.

**Comment by swgmike** [comment]
@vinsworldcom the autocompletion DTD has a few parameters that the xsd doesn't such as language, 

I'm wondering if the DTD is specified in the schema file, that the xmltools will be able to validate the structure of the schema xsd. If so, it probably wouldn't hurt to have it added the NPP distro too. 

since youve submitted other xsds for functionlists and userdefinedlang it may provide the capability to validate them using xmltools by specifying the namespace attributes that I did as directory paths.  This will help prevent errors from typos and mistakes from being written to the saved files. Same for the dtds for these too.

@pryrt  as for the purpose of the language attribute, I understand that NPP doesn't use it, but there are two interpretatons for its use: 1) to specify the language such as french,english, german etc or its short form as en-US, FR, DE, and 2) to specify the computer language that the autocomplete xml files is written for vs. having to look at the filename and as a method of documentation for the file.

**Comment by vinsworldcom** [comment]
> the autocompletion DTD has a few parameters that the xsd doesn't such as language

I don't think so?

![image](https://user-images.githubusercontent.com/9657169/216728972-6a4d6981-4165-4ed4-94a0-9974302adc0e.png)

**Comment by swgmike** [comment]
@pryrt 
Since there are multiple ways to point/retrieve the xsd file for validation of the xml file, I've listed why some are better than others.
1). retrieve the xsd via website.   Disadvantage: May not be editable to use even if downloaded to a disk since the schemalocation still points to the website that everyone can save their changes there. Also if one has no internet connection, one can't retrieve the xsd during validation.
2). retrieve xsd file from full pathname. Disadvantage, although one will know exactly were its stored at, one will have to edit it manually should NPP be installed on ones computer on a different disk drive (portable or partition), and/or in a different install directory. This will require one to manually edit the full pathname assigned to the schemalocation to point to the new drive letter and full path location.
3). retrieve the xsd file without full pathname. Disadvantage, the xsd must reside in the same directory as the xml file being validated. However, it eliminates the portability problem of pointing to a different drive letter or directory path.
4). retrieve the xsd file via a relative directory pathname. Disadvantage: same as item (3) , but eliminates the restriction of the xsd having to be in the same directory as the xml file being validated. Having a different subdirectory allows one to group similar files together from the other files for easy configuration maintenance. See below for the other variation.
a). First example is a schema subdirectory created in the autocompletion directory that the xml file is in.
b). Second example has the schema subdirectory at one or more parent directory levels relative to the autocompletion diirectory that the xml file is in.

<NotepadPlus
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="schema/NotepadPlus.xsd"
>

Parent directory level

<NotepadPlus
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="../schema/NotepadPlus.xsd"
>

5). Via a batch file external to NPP like @vinsworldcom  has posted.

6). Import the xsd and xml into an commericial xml tool and do the validation and editing there and then save the changes back to NPP directory location(s).

So, for your user manual changes, you can mention any of these for others to follow when they do validation.

You can also mention in the user manual that the language attribute can be used for documenting the autocompletion file although NPP doesn't use it for purposes such as country language of en-US,FR,DE... or the language that the autocomplete xml file is intended for such as "C" or "DXL" etc since the xml filename may not specify a full name more detailed name with punctuation that this attribute would.

Others can play around to get the schemaLocation attribute and namespaces to work that I have commented out. The noNamespaceSchemaLocation attribute currently works. 

Be aware that the xsd file I posted will also enforce the NPP xml file attribute values allowed such as expected characters, and their lengh too. You can test this to see what happens with a good xml file to understand what limitations the xsd has in finding typo errors that a user can make.

**Comment by swgmike** [comment]
@vinsworldcom 
I made a modeto the batch file to put a pause before the end so that it will stop to give me a chance to see the processing results.
I moved the userdefinedlangs dtd and xsd to the notepad roaming subdirectory with same name, but it can't find the dtd and xsd that are there.
Moreover, xmllint command isn't found on my windows 10 system. Thus, which distro will install this tool?

**Comment by pryrt** [comment]
> Moreover, xmllint command isn't found on my windows 10 system. Thus, which distro will install this tool?

He already said, 

> `xmlcheck.bat` assumes you have `xmllint.exe` in your path somewhere - mine is from Strawberry Perl, but it also exists as part of Git for Windows.

**Comment by pryrt** [comment]
FYI: The main description for validating using these files _won't_ be going in the User Manual itself: Don has requested of me that how-to guides and other "tangential" information instead it be made a FAQ in the Notepad++ Community (like what MAPJe71 published in [FunctionList Basics](https://community.notepad-plus-plus.org/topic/19480/faq-desk-function-list-basics/1)), because he wants the manual to focus on the core usage of Notepad++. And if the descriptions are going in the FAQ, I might look into somehow embedding the XSD files directly in the FAQ in the Forum: apparently, as a moderator, I might have the power to embed file types other than just images in forum posts... if I can get that to work, I might put the individual XSD files or a single zipfile in the FAQ.

**Comment by pryrt** [comment]
I have a draft for the FAQ [here](https://github.com/pryrt/nppStuff/blob/main/CommunityForum/FAQ/ValidatingConfigXML.md).  I think I have boiled down the information into a usable set of instructions.  Before I post it to the Forum's FAQ section, I'd like to make sure I haven't missed anything essential from our conversation.

**Comment by pryrt** [comment]
(The "closing" was w/r/t to adding the validators to the UDL repo itself.  Feel free to still make comments on the FAQ draft here.
