### ISSUE TITLE
Koltin

### ISSUE THREAD

**Issue by rainman-wf** [notepad-plus-plus/userDefinedLanguages#164]
Hello! It,s great job, guys, but what about kotlin language?

**Comment by pryrt** [comment]
If you have a UDL for the Kotlin language, feel free to submit it.  If you do not, feel free to create it, and then submit it to the repo once it was ready.

(This repository is for user-submitted UDL languages; the maintainers of the repo have not been tasked with creating UDL definitions on request, but with facilitating the submission of user-submitted UDL definitions.)
