### ISSUE TITLE
Missing UDL file- RenderMan-RSL_by-focus_gfx.xml

### ISSUE THREAD

**Issue by JourneysFutpath** [notepad-plus-plus/userDefinedLanguages#166]
Got the ol' 404 when trying to get the above UDL- Is this something that has been permanently removed from this repo or do I still stand a chance at getting it at a later time? 🍻

![image](https://user-images.githubusercontent.com/124089707/234977431-82d5ba70-51ec-40f2-96e9-c83c0f3fd83e.png)

**Comment by pryrt** [comment]
It's not a UDL file, and it never was.  It is actually an auto-completion definition file.

https://github.com/notepad-plus-plus/userDefinedLanguages/blob/master/autoCompletions/RenderMan-RSL_by-focus_gfx.xml

The URL was wrong in the .md, and it was grouped with the UDLs.  I will work on getting links to the auto-completion definitions as well, and move that (corrected) link to a separate group of links, so it's obvious it's an auto-completion file.

**Comment by JourneysFutpath** [comment]
I apologize- I should've said xml. Thanks a million!
