### ISSUE TITLE
Bad display of cue syntax

### ISSUE THREAD

**Issue by NetCzech** [notepad-plus-plus/userDefinedLanguages#171]
Hello,
syntax for cue sheets is not displayed correctly in dark mode.

![n++_cue](https://github.com/notepad-plus-plus/userDefinedLanguages/assets/76791894/c2c1dcae-a7b1-4a70-9542-1c8b22b30d3e)

**Comment by pryrt** [comment]
1. We don't really _maintain_ the user-supplied UDL definitions, we just store them for easy distribution.
2. UDL definitions are theme/mode specific.  If you want a UDL for "cue" that works well in Dark Mode, you will have to change the colors yourself.  If you want to share your updated UDL with other Notepad++ users, you can upload your "Dark Mode" version of the cue definition to this repository, so people can then choose whether to download the normal or the Dark Mode version, as appropriate for their Light-vs-Dark desires.
