### ISSUE TITLE
Looking for help to define column-oriented languages

### ISSUE THREAD

**Issue by abekornelis** [notepad-plus-plus/userDefinedLanguages#247]
I am an addict of HLASM - a language that is heavily columnar in nature.
I have been able to create syntax highlighting, but it is a bit of a kludge. 
It is quite likely I am not using NPP facilities in an optimal way. I did read doco I could find, but there seem to be some gaps.
I'd like to find out if I am indeed missing something. And otherwise, what can be done to improve NPP support for columnar languages such as HLASM. (And RPG to name but one other)

**Comment by abekornelis** [comment]
For those who care to know the details, the syntax rules (slightly simplified) for HLASM are as follows:
1. if col 1 contains '*' (star) it is a comment line
2. if col 1-2 contains '.*' (dot-star) it is a comment line
3. if column 1 starts with anything else, it is a label:
3a. if the label starts with a dot, it's a macro label
3b otherwise it is an assembly label
4. the next token on the line is the operation code (always delimited by leading and trailing blank)
5. after the operation code follow all arguments, this is a comma-delimited list, without embedded blanks, except inside strings which are enclosed in apostrophes.
6. the arguments are terminated by a space, anything that follows is a comment
7. any non-blank in column 72 indicates that the list of arguments is continued on the next line
8. continuation lines must contain blanks in column 1-15
9. there can be as many continuation lines as needed
10. Continued lines can have arguments up to column 71, or they can end in a comma-space. Either way the source continues on the next line in column 16. (so you can have comments on each line of a multi-line statement)
11. Strings must continue up to column 71 and are resumed on the next line, column 16, if a continuation marker is present in column 72. No additional quotation marks are allowed.
12. blank lines are allowed, but not in the middle of a series of continuation lines.
13. Source data and/or columns never extend beyond column 80.

**Comment by pryrt** [comment]
First: it should be noted that this User Defined Language Collection is solely for collecting and distributing user-created UDL definitions.  Nothing that happens in this repository can control/influence how Notepad++ processes UDL or what features Notepad++ includes.

To respond to your question / request for help: you have interpreted correctly: UDL is incapable of doing such intricate column-based decisions.  UDL was designed as a simple keyword highlighting solution when one of the 80+ built-in languages didn't match your specific language, but it was not, and will not be, for doing complicated or advanced syntax highlighting (like you suggested) -- many features, like regex-based keyword matching, or folding-by-indentation (like Python), or column-based meaning (like Fortran or the languages you have described) cannot be replicated in the simple UDL interface.

Notepad++ uses a library called "Lexilla" to provide the 80+ built-in languages.  When those languages aren't sufficient, a user is encouraged to try doing a UDL for their language, but that won't be sufficient for all cases.  The next level of defense is that the Notepad++ plugin infrastructure allows for writing a [lexer plugin](https://npp-user-manual.org/docs/plugins/#building-a-lexer-plugin), which behaves like one of the built-in languages, but is installed through the normal plugin interface -- the most famous example being the GEDCOM lexer plugin (which is available through the Plugins Admin) -- I understand and admit that not everyone has the skill or time to invest in developing a whole plugin.  The final recourse is to create an [issue at the Lexilla project](https://github.com/ScintillaOrg/lexilla/issues) requesting that they create a lexer for your language (but I've been given the impression over the years that they rarely write new lexers themselves now that they've got so many major languages already covered; instead, they encourage other people to write the lexer, and then submit a PR to put it into their project)

**Comment by abekornelis** [comment]
Thanks for the elaborate explanation. I might be able to create it if I had enough time on my hand. Wish it were so, that would be a nice fun project to work on. For now I'll accept that what we have is the best I can do for the time being. Kind regards, Abe.
