### ISSUE TITLE
Add Unit Tests for functionList submissions to the UDL Repo

### ISSUE THREAD

**Issue by pryrt** [notepad-plus-plus/userDefinedLanguages#255]
> Missing unit test for the function list.

_Originally posted by @MAPJe71 in https://github.com/notepad-plus-plus/userDefinedLanguages/pull/253#pullrequestreview-2114294604_

**Comment by chcg** [comment]
@pryrt See https://github.com/notepad-plus-plus/notepad-plus-plus/blob/f2e5739d4d55da92ac240d38d6323e57abe92840/.github/workflows/CI_build.yml#L226-L242 regarding unittests for functionlists . Could also be done with a released N++ version with the additional unittest folder with modification needed for UDL functionlist testing.

**Comment by pryrt** [comment]
@chcg,
> See https://github.com/notepad-plus-plus/notepad-plus-plus/blob/f2e5739d4d55da92ac240d38d6323e57abe92840/.github/workflows/CI_build.yml#L226-L242 regarding unittests for functionlists . Could also be done with a released N++ version with the additional unittest folder with modification needed for UDL functionlist testing.

Hmm.  That looks like it could be complicated -- I mean, I know how to download a copy of Notepad++ in a GitHub action (I used chocolatey for that on my Win32::Mechanize::NotepadPlusPlus perl module), so in theory, I could try to bring the components together in this repo as well.  But is it really worth the effort for _this_repo?

I am especially wondering if the "barrier to entry" would be too large for a "community" contribution.  I completely agree that functionList definitions that are submitted to the main N++ application to go with the built-in languages should undergo full scrutiny.   Developing a functionList that "works for me" is hard enough for a normal user; trying to understand how to develop and submit a unit test on top of it is a "big ask".

And this userDefinedLanguages repo is meant as a user-friendly place to share their UDL (and associated files).  If the "barrier to entry" is too high, they aren't likely to make use of the Collection to share functionLists for their submitted UDL.  

What do @chcg and @MAPJe71 think of the cost-benefit analysis: is it really worth the effort of me porting the testing framework to this repo? And is it worth the extra effort required for every person who wants to submit their UDL's functionList to this repo?  If the framework is implemented, should we _require_ the users submit a unit test, or should it just be encouraged?

**Comment by chcg** [comment]
@pryrt I agree that this is some effort to implement and get working. From a contributor just a sample file for the new language needs to be provided that shouldn't be a too big step. The rest probably should be done by the repo maintainer (checking that the reference file makes sense and adding the new language to the overrideMap.xml, etc. )

The main benefit I think would be that modifications to an existing functionlist don't cause regressions.

**Comment by MAPJe71** [comment]
@pryrt 

> What do @chcg and @MAPJe71 think of the cost-benefit analysis: is it really worth the effort of me porting the testing framework to this repo?

To be able to run the unit tests as they are used in the main Notepad++ repository, it has to be possible to run Notepad++. With the right command line arguments it creates a JSON file that represents the functionList-tree as it would be visible in Notepad++.

I don't think it's maintainable to keep a copy of the Notepad++ executable in this repo just to be able to run the unit tests.

> And is it worth the extra effort required for every person who wants to submit their UDL's functionList to this repo? 

IMO it's a way for the submitter to "prove" that enough effort was put in the functionList-parser i.e. using the parser on the included sample file will give the expected result.
Furthermore, it can be used to check for regressions.

> If the framework is implemented, should we require the users submit a unit test, or should it just be encouraged?

IMO we should require a sample source file and the corresponding JSON reference file to complement the submitted parser.

**Comment by pryrt** [comment]
The consensus is that it's worth having the Unit Test for functionList submissions to this Collection, so I will keep this issue open, and work on it as I have time.

Once it's working, I will also add in the rules (and checks) so that if there's a functionList submitted for a given UDL, the example file _and_ the JSON-output-file are required to also be present.

Thanks for the input.
