### ISSUE TITLE
@MAPJe71,

### ISSUE THREAD

**Issue by MAPJe71** [notepad-plus-plus/userDefinedLanguages#258]
My bad, I totally missed that this is _not_ in the Notepad++ main repository.

> do those unit tests require access to notepad++.exe?
Yes, Notepad++ is called with the appropriate/special command line arguments.
It runs "headless" and creates a JSON file which contains a representation of the `functionList`-tree. This JSON output is then compared to the reference JSON to determine whether or not the applicable parser works as expected.

> And thank you for the detailed point-by-point commentary for the fixes that need to go in the functionList definition

You're welcome.

**Comment by pryrt** [comment]
I don't think GH lets us easily _delete_ an issue.   We can just leave it here and closed.
