### ISSUE TITLE
WDL language definition file

### ISSUE THREAD

**Issue by fangdongming** [notepad-plus-plus/userDefinedLanguages#270]
Hi, 
There is no WDL language definition file, Could you added the WDL.xml ?
WDL, Workflow Description Language;

Thank you.

**Comment by pryrt** [comment]
I'm sorry that this wasn't clear before, but as the README now makes explicit:

The maintainers of this Collection do not have the knowledge to make a custom User Defined Language definition on request -- you likely know your Language much better that we do (for example, I've never heard of "WDL" as a language).  

It is super simple to make your own UDL: paste your language's keywords into one or more of the eight keywords sections, put the appropriate operators into the operators inputs, possibly add some limiters (like quote-pairs or parentheses pairs) and/or comments definitions and/or folding definitions; set the colors to match your desire, and enjoy.  

You can see the online User Manual's [UDL description](https://npp-user-manual.org/docs/user-defined-language-system/) with the details on what all of those mean, and how to use it.  Once you have a working UDL, you can share it with others by [Contributing to the Collection](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/CONTRIBUTING.md).
