### ISSUE TITLE
[Request] Add smali

### ISSUE THREAD

**Issue by 7wells** [notepad-plus-plus/userDefinedLanguages#36]
Hello,

Could you please consider adding the 'smali' highlighting to the list?
https://github.com/Jasi2169/smali-syntax-highlighting-for-notepad-

I am not the author, though. Please accept my apologies if this is not the right place to propose this. Thank you.

**Comment by chcg** [comment]
@7wells You could create a PR for that also you are not the originating author, see https://github.com/notepad-plus-plus/userDefinedLanguages/blob/master/CONTRIBUTING.md .
