### ISSUE TITLE
Default UDL of XML

### ISSUE THREAD

**Issue by younesZdDz** [notepad-plus-plus/userDefinedLanguages#51]
Hello,

I am working on adding a new language that has an XML based syntax, so I looked everywhere for the default UDL of XML that is used in notepad++ to inspire from it, and I couldn't find it. 
Could you put the UDL definitions of all the default supported languages by notepad++ (javascript, HTML...) in this repository, could be really helpful.

Thanks a bunch.

**Comment by chcg** [comment]
@younesZdDz The builtin parsers are not realized as UDLs but via lexers in C++ code from scintilla, see https://github.com/notepad-plus-plus/notepad-plus-plus/tree/master/scintilla/lexers.

**Comment by younesZdDz** [comment]
Okay thank you for the response!

**Comment by Zack-83** [comment]
@younesZdDz Did you succeed in "translating" the parser for XML from the Scintilla Lexer into a UDL description?
I would like to do the same for other languages, namely
HTML + Python --> Django
R + Markdown --> Rmarkdown
but I have no idea how to start.
