### ISSUE TITLE
Some Keywords can't be highlighted

### ISSUE THREAD

**Issue by Tholwin** [notepad-plus-plus/userDefinedLanguages#65]
I need to highlight some very unconventional keywords, but some of them are not recognized.
I have UDL v.2.1.0.12

I defined the following list of "keywords", in the same group :
"45 53 BD 11" "12 E2 D3 DE" "F8 FB 00 00 00 00" "8E 69 32 B3"

The styling works for the following strings :
F8 FB 00 00 00 00
8E 69 32 B3

But the styling doesn't work for the following strings :
45 53 BD 11
12 E2 D3 DE

**According to my observations, it's as if keywords are not allowed to start with more than 1 digit, zeroes being ignored.**
To illustrate this,
Styling can be applied to these 3 keywords :  00A 10A 100A
Styling can't be applied to these 3 keywords :  01A 11A 1001A

(The context menu custom styling isn't a satisfying workaround, because it has to be redone for every files.)

**Comment by pryrt** [comment]
This userDefinedLanguages repo is actually just for holding user-submitted UDL definitions, but cannot influence the codebase (ie, how it parses files).  I don't have the power to transfer your issue from this repo to the [main application issues](/notepad-plus-plus/notepad-plus-plus/issues), so if you want to report this as a bug, you'll unfortunately have to manually re-submit (and UDL bugs/feature-requests are unfortunately not the highest priority).

However, I can offer the advice that I often give in the [Community Forum](https://community.notepad-plus-plus.org/) when people find things that don't work quite as desired in the UDL system: you can add extra highlighting to any lexer, including a User Defined Language (UDL), using regexes via the script `EnhanceAnyLexer.py` that @Ekopalypse shares [in his github repo](https://github.com/Ekopalypse/NppPythonScripts/blob/master/npp/EnhanceAnyLexer.py).  This is probably your most efficient path to getting the highlighting you want, but you have to be willing to install the PythonScript plugin.

**Comment by Tholwin** [comment]
Awesome! With this, I can do what I need, and even more.
Thank you so much!
