### ISSUE TITLE
Add UDL for EDN

### ISSUE THREAD

**Issue by leodoi3** [notepad-plus-plus/userDefinedLanguages#72]
Add customized User Defined Language (UDL) for Notepad++ for syntax highlighting of EDN data language based on [edn-format ](https://github.com/edn-format/edn)

**Comment by pryrt** [comment]
If you want to develop a UDL that works for you, and share it in the repository, then great, feel free to re-open this issue, and submit a PR against it.  

But the maintainers of the User Defined Languages repository are here just to help people distribute UDL that have already been created; this repository is not a UDL-creation service.

It's really not that difficult to create the UDL for a language you know : you just put the keywords and operators into appropriate fields in the dialog, adding colors for each different category of keyword using the **Styler** button, and maybe define the folding if you want to make code folding easy.  The overview in the main [Notepad++ online User Manual](https://npp-user-manual.org/docs/user-defined-language-system/) and the UDL deep-dive at https://ivan-radic.github.io/udl-documentation/ will help if you are trying to do slightly more complicated highlighting.

Once someone creates a UDL for a language they know, and they want to share it, we maintainers can help them get it into the repository; but we are not here to write random UDL upon request.
