### ISSUE TITLE
Nesting issue with keywords and delimiter 

### ISSUE THREAD

**Issue by LX222** [notepad-plus-plus/userDefinedLanguages#75]
Example:

I have a language that works with simple commands at the start of a line (SCREENSHOT .. ,  RESET , etc.)
An example of a command line would be

`SCREENSHOT myfile.png`

Now I want to highlight such lines, but with the command itself in bold:
**SCREENSHOT** _myfile.png_

-------------------------------------

If I define 
Keyword1:
"SCREENSHOT"

Delimiter1:
Start = "SCREENSHOT" 
End = "((EOL))" 
Nesting= Keyword1

then Keyword1 will not be matched.
The problem seems, that nesting only looks for a string AFTER the "Start"-match.

Is there any workaraound?

**Comment by pryrt** [comment]
UDL is great for simple things, but it cannot do everything.

With just the UDL feature, no, there isn't a workaround.  However, you can add extra highlighting to a builtin lexer or to a User Defined Language (UDL) using regexes via the script `EnhanceAnyLexer.py` that @Ekopalypse shares [in his github repo](https://github.com/Ekopalypse/NppPythonScripts/blob/master/npp/EnhanceAnyLexer.py) -- install the PythonScript plugin, then "create a new script" and paste in the `EnhanceAnyLexer.py`; there is more documentation inside the comments in that script, which should explain how to install and run it.

If you need further help with that script, you can go to the [Notepad++ Community Forum](https://community.notepad-plus-plus.org/), and make a post where you show what you tried and ask for help, including an @-mention of the author @Ekopalypse, and he or I or one of the other regulars there should be able to help you.
