### ISSUE TITLE
GO template doesnt work

### ISSUE THREAD

**Issue by Revertron** [notepad-plus-plus/userDefinedLanguages#88]
Trying to use [this xml](https://github.com/notepad-plus-plus/userDefinedLanguages/blob/master/UDLs/go_byAnthonyStarks.xml) to import Go language template. It is not working.

**Comment by pryrt** [comment]
Apparently, no one had tried it since it was uploaded to the repo -- it didn't have valid XML structure.  Once I fixed that, I was able to put it in my `userDefineLangs\` folder and it highlights example Go code.  So you should try downloading the updated version.

**Comment by Revertron** [comment]
But I've tried that. Didn't work either :-/

**Comment by pryrt** [comment]
> But I've tried that. Didn't work either :-/

It works for me.  Are you sure you tried after I fixed the file?

1. Close Notepad++
2. Download go_byAbthonyStarks.xml into correct `userDefineLangs\` folder (most likely `%AppData%\Notepad++\userDefineLangs\`  , depending on your installation
3. Start Notepad++
4. **Languages > go** is available 

If that is not your experience, you will have to give more details as to what's not working.  (For example, supply your **Debug Info**, along with directory listings of where you put the downloaded file to prove it's where it should be)

**Comment by Revertron** [comment]
Yep, I've redownloaded that xml to this directory:
![image](https://user-images.githubusercontent.com/105154/155015723-17d48730-fb34-4eea-a2ec-53c3e2215b92.png)
Restarted the Notepad++, and there is no Go language in **Languages** menu :(

Here is Debug Info:
```
Notepad++ v8.2.1   (32-bit)
Build time : Jan 19 2022 - 18:38:49
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : D:\*****\*****\NextCloud\Configs
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 2009
OS Build : 19044.1566
Current ANSI codepage : 1251
Plugins : mimeTools.dll NppConverter.dll NppExport.dll NPPJSONViewer.dll NppSaveAsAdmin.dll 
```

**Comment by pryrt** [comment]
You said,
> ```
> Cloud Config : D:\*****\*****\NextCloud\Configs
> ```

There's your problem.  Your _active_ userDefineLangs folder is `D:\****\****\NextCloud\Configs\userDefineLangs\`.

https://npp-user-manual.org/docs/config-files/ =>
> If you enable the [Cloud settings](https://npp-user-manual.org/docs/preferences/#cloud), some configuration files will go in the defined directory (including contextMenu.xml, shortcuts.xml, userDefineLang.xml, langs.xml, stylers.xml, and config.xml; the userDefineLang\ subfolder can be placed there as well, though it won’t be created by default when the Cloud settings folder is first populated).

So if you want this Go language UDL active, the config file needs to go in the cloud config hierarchy, not in the AppData hierarchy.

**Comment by Revertron** [comment]
Ah, thanks!
I didn't remember that I've configured that.
Thanks a lot, now it works!
