### ISSUE TITLE
Create dark mode styles

### ISSUE THREAD

**Issue by r-bird** [notepad-plus-plus/userDefinedLanguages#90]
Most of the styles do not work with the dark mode themes of Notepad++, e.g. because the foreground color is black(ish).

**Comment by pryrt** [comment]
Indeed.  Anyone who wants to may [contribute](https://github.com/notepad-plus-plus/userDefinedLanguages/blob/master/CONTRIBUTING.md) a dark-mode variant of a UDL to this repository.

But I and the other maintainers of this repository are just here to help with the github portion (manage pull requests, or convert issues that include a full UDL file into a PR if the submitter doesn't understand how).  We are not here to create UDLs on demand, but to help other people share the UDLs that they've already created.
