### ISSUE TITLE
Request: DAX PowerBI

### ISSUE THREAD

**Issue by tidypy** [notepad-plus-plus/userDefinedLanguages#96]
Please add the DAX language for PowerBI.   
[dax-xml.zip](https://github.com/notepad-plus-plus/userDefinedLanguages/files/8855799/dax-xml.zip)
SOURCE:  https://sascha-kasper.com/dax-syntax-highlighting-for-notepad/
SOURCE 2:  https://community.powerbi.com/t5/Developer/DAX-syntax-highlighting-in-Notepad/m-p/363293

**Comment by pryrt** [comment]
The zip file you provided is the autocompletion file, _not_ the UDL definition.  Please include the UDL definition XML as well.
